### PR TITLE
Fix smol Vim accident

### PR DESCRIPTION
**Pull request by jonathanperret**
This doesn't look intentional 😉

### CODE REVIEW

**Review by metasyn — APPROVED** [review]
Wahhhh haha yes this is definitely a typo. Thanks @jonathanperret !

**Comment by metasyn** [comment]
Oh shucks. It looks like from the build its creating a git conflict. Would you be willing to just make the change to the site/index.html? Or I can make the change manually

**Comment by jonathanperret** [comment]
Sorry, I'm not sure I understand how the automated build is set up — I'm puzzled that it created a commit on my PR branch? 😓 
Anyway, I just rebased my change to `site/index.html` on top of the latest `master`, will this work?

**Comment by metasyn** [comment]
Yes, that is perfect! Thanks Jonathan :bow:

**Pull request merged**
